### ISSUE TITLE
[BUG] App keeps scanning and fields are not available

### ISSUE THREAD

**Issue by Scridgeon** [alexVinarskis/dell-powermanager#22]
All of the sections under Battery Settings and Thermal Management have a blue scanning bar that goes across them. The scanning persists and the fields never become available to use.

To Reproduce:
1. Open App
2. Go To Battery Settings section
3. Blue scanning indicator constantly scrolls over fields on the right. 

Expected behavior:
The fields should be available to use when entering that section of the app.

![image](https://github.com/alexVinarskis/dell-powermanager/assets/18316138/6020234c-c677-4f3c-8574-bf444d44b0b0)

Device Info:
 - OS: [6.5.0-13-generic, Ubuntu 23.10]
 - Platform [Dell Inc. XPS 13 9360]
 - App Version [0.8.0+20231126-193826]

**Comment by alexVinarskis** [comment]
Hi, thanks for the report. It seems like app cannot get response from Dell's CCTK. A few things to check:
* I assume you have, but just to make sure: have you installed all of the dependencies? Upon start of the app, bottom left corner would have yellow warning indicator that CCTK is missing, and for ubuntu it can be installed automatically
* Can you run Dell's CCTK manually? If installed via integrated installer, path would be `sudo /opt/dell/dcc/cctk`, and it shall be run as root/sudo. Sample output:
```
$ sudo /opt/dell/dcc/cctk --version

Dell Command Configure Version 4.10.0  5 (Linux - Dec 16 2022, 13:02:46)
Copyright 2009 - 2023 Dell Inc. All rights reserved.
```
* Could you please run app via terminal, and attach the log file? via `dell-powermanager > log.txt`. Fyi log will contain all battery info as seen on the first page, including battery's serial number, in case you would like to redact it

**Comment by Scridgeon** [comment]
cctk: Dell Command Configure Version 4.11.0  6 (Linux - Aug  9 2023, 10:29:26)

log file is attached.
[log.txt](https://github.com/alexVinarskis/dell-powermanager/files/13596935/log.txt)

**Comment by Scridgeon** [comment]
cctk -H : [cctk.txt](https://github.com/alexVinarskis/dell-powermanager/files/13610784/cctk.txt)

cctk -H --ThermalManagement : [cctk_thermal.txt](https://github.com/alexVinarskis/dell-powermanager/files/13610791/cctk_thermal.txt)

cctk -H --PrimaryBattChargeCfg : [cctk_battcfg.txt](https://github.com/alexVinarskis/dell-powermanager/files/13610798/cctk_battcfg.txt)

**Comment by alexVinarskis** [comment]
fixed by https://github.com/alexVinarskis/dell-powermanager/pull/26
