### ISSUE TITLE
[TESTED DEVICE] Vostro 5401

### ISSUE THREAD

**Issue by Aldmors** [alexVinarskis/dell-powermanager#23]
**Summary**
Positive experience.  
Everything work
**Screenshots**
If you experienced issues, add screenshot of the bug. If everything is okay, add screenshot of the app and system info screen with device model/OS version...

**Device Info (please complete the following information):**
 - OS: Ubuntu 23.10
 - Platform Dell Vostro 1503
 - App Version 0.8.0

**Additional context**

Before the last update, installing drivers did not work, but now it has been fixed

**Comment by alexVinarskis** [comment]
Thanks for testing, and for you report! I will add your machine to list of supported devices in README.

> * Platform Dell Vostro 1503

I cannot seem to find the model online. Could you please provide the full model number, or service tag, or link to the model on Dell website?

> Before the last update, installing drivers did not work, but now it has been fixed

Indeed, there was an issue with broken link to `libssl` installation, apologies.

**Comment by Aldmors** [comment]
Sorry, I got my model number wrong

https://www.dell.com/support/home/en-uk/product-support/product/vostro-14-5401-laptop/overview

Vostro 5401

**Comment by alexVinarskis** [comment]
added
