### ISSUE TITLE
[FEATURE]flatpak or OBS (for opensuse)

### ISSUE THREAD

**Issue by poltpolt** [alexVinarskis/dell-powermanager#30]
Hi,
I have failed to build on Opensuse,
for less technical ppl and popularity of your program it would be great to have it on flathub that climbs in popularity

**Comment by alexVinarskis** [comment]
Hi, thanks for the suggestion.
I have already planned to put it on either flatpak or snap, however its not the time just yet, as its still in Beta stage. I hope to get it there within a few months.

Wrt to failed build, what exactly was the issue? Perhaps for the time being I could improve readme if any of the steps are missing.

**Comment by poltpolt** [comment]
I was not aware binaries were provided, sry I missed it in readme probably.
the amd64 works fine in opensuse TUbleweeed now :) perfect.

For snaps and flathub I understand it is not easy, I gave up with my soft after some hours reading trought flathub requirements.
