### ISSUE TITLE
[BUG] Master branch version issue

### ISSUE THREAD

**Issue by poltpolt** [alexVinarskis/dell-powermanager#35]
Building from up to date master results in version 0.1.0 inferior to latest release version
![obraz](https://github.com/alexVinarskis/dell-powermanager/assets/9408405/b44d4d32-f28e-4c4b-95d8-5e74826d3397)

**Comment by alexVinarskis** [comment]
Please build via `package.sh`. Even if it will not package .deb for non debian systems, it sets required variables, including version number from git.

**Comment by alexVinarskis** [comment]
Solved?

**Comment by alexVinarskis** [comment]
Assumed resolve due to non-reply & solution provided
